import Head from 'next/head';
import Header from '../components/ui/Header';
import TopCards from '../components/ui/TopCards';
import BarChart from '../components/ui/BarChart';
import RecentOrders from '../components/ui/RecentOrders';
import router from 'next/router';
import Cookies from 'js-cookie';
import { USERNAME } from '../utils/tokenHelpers';
import { useState } from 'react';
import ErrorComponent from '../components/ui/Error';

export default function Home() {
  const [error, setError] = useState<string | null>('');

  const handleButtonClick = async () => {
    try {
      const res = await fetch('/api/logout', {
        method: 'POST',
      });
      if (res.ok) {
        router.push('/auth/signin');
      } else {
        throw new Error(`${res.statusText}`);
      }
    } catch (error: Error | any) {
      setError(`Oops, something went wrong:, ${error.message}`);
      console.log(error.message);
    }
  };

  const fullName = (() => {
    try {
      return Cookies.get(USERNAME) || '';
    } catch (error: any) {
      // setError(`Error getting fullName cookie:, ${error.message}`);
      console.log('Error getting fullName cookie:', error.message);
      return '';
    }
  })();

  return (
    <>
      <Head>
        <title>MemberMQ</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <main className='bg-gray-100 min-h-screen'>
        <Header
          pageTitle='Dashboard'
          userName={fullName !== '' && fullName !== null ? fullName : ''}
          onClick={handleButtonClick}
          buttonName='Log Out'
        />
        <div>
          {error && <ErrorComponent message={error} onClose={() => setError('')} />}
        </div>
        <TopCards />
        <div className='p-4 grid md:grid-cols-3 grid-cols-1 gap-4'>
          <BarChart />
          <RecentOrders />
        </div>
      </main>
    </>
  );
}
