import Head from 'next/head';
import Header from '../components/ui/Header';
import TopCards from '../components/ui/TopCards';
import BarChart from '../components/ui/BarChart';
import RecentOrders from '../components/ui/RecentOrders';
import router from 'next/router';

export default function Home() {
  
  const handleButtonClick = async () => {
    try {
      const res = await fetch('/api/logout', {
        method: 'POST',
      });
      if (res.ok) {
        router.push('/auth/signin');
      } else {
        console.log('Cannot Logout User at this moment');
      }
    } catch (error) {
      console.error(error);
    }
  };

  return (
    <>
      <Head>
        <title>MemberMQ</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <main className='bg-gray-100 min-h-screen'>
        <Header
          pageTitle='Dashboard'
          userName='User'
          onClick={handleButtonClick}
          buttonName='Log Out'
        />
        <TopCards />
        <div className='p-4 grid md:grid-cols-3 grid-cols-1 gap-4'>
          <BarChart />
          <RecentOrders />
        </div>
      </main>
    </>
  );
}
